#!/usr/bin/env Rscript

argv <- commandArgs(TRUE)

usage <- function() {
	print("Usage: plot* <data>")
	quit()
}

if (length(argv) < 1) {
	usage()
}

argv <- commandArgs(TRUE)

library(ggplot2)

d <- read.table(argv[1], header=TRUE, stringsAsFactors=FALSE)
hist <- d[d$Count > 0, ]
summary(hist)

da <- aggregate(x = as.numeric(d$Count), by = list(d$Name), FUN=sum)
colnames(da) <- c("Value", "Count")
total <- sum(da$Count)
da$Fraction <- da$Count / total
da$Percent <- sprintf("%.9f", da$Fraction * 100)
da <- da[da$Count > 0, ]
da <- da[order(da$Count),]
print(da, row.names=FALSE)

plot_1 = ggplot() +
	geom_bar(data=hist, aes(x=as.factor(Value), y=Count, fill=Ops), stat="identity", position="stack") +
	ggtitle(paste("Counts in", argv[1])) +
	xlab("Value") +
	ylab("Count") +
	scale_x_discrete(breaks=as.factor(hist$Value), labels=parse(text=hist$Name)) +
	#theme with white background
	theme_bw() +
	#eliminates background, gridlines, and chart border
	theme(
	plot.background = element_blank()
	,panel.grid.major = element_blank()
	,panel.grid.minor = element_blank()
	,panel.border = element_blank()
	) +

	#draws x and y axis line
	theme(axis.line = element_line(color = 'black')) +

	theme(axis.text.x = element_text(angle=90, hjust=0.5, vjust=0.5, size=6))

ggsave(filename=paste(argv[1], ".png", sep=""), plot=plot_1, height=5, width=6)
